# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CedanaCli < Formula
  desc ""
  homepage "cedana.ai"
  version "0.2.1"

  on_macos do
    url "https://github.com/cedana/cedana-cli/releases/download/v0.2.1/cedana-cli_0.2.1_darwin_amd64.tar.gz"
    sha256 "942359d8971777ed6f9c0852c130e9a5c96cf75560d2c45319cbba73dc8d80ea"

    def install
      bin.install "cedana-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the CedanaCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cedana/cedana-cli/releases/download/v0.2.1/cedana-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "b20302ddee1b68de37e284e81e931d4873678f150e0aa7cfa216f03f2fccade6"

      def install
        bin.install "cedana-cli"
      end
    end
  end
end
