# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CedanaCli < Formula
  desc ""
  homepage "cedana.ai"
  version "0.2.7"

  on_macos do
    url "https://github.com/cedana/cedana-cli/releases/download/v0.2.7/cedana-cli_0.2.7_darwin_amd64.tar.gz"
    sha256 "d5b62da8574ca37664038610f0624713124aa6f455f3a8ea60b252845fa04fcf"

    def install
      bin.install "cedana-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the CedanaCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cedana/cedana-cli/releases/download/v0.2.7/cedana-cli_0.2.7_linux_amd64.tar.gz"
      sha256 "89bb03ad116987dca7e8a44e7a03266e74f5b38c90790581c5f6b71fd7e30db7"

      def install
        bin.install "cedana-cli"
      end
    end
  end
end
