# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CedanaCli < Formula
  desc ""
  homepage "cedana.ai"
  version "0.2.6"

  on_macos do
    url "https://github.com/cedana/cedana-cli/releases/download/v0.2.6/cedana-cli_0.2.6_darwin_amd64.tar.gz"
    sha256 "680eeb72f5f5d4b99871e5f7e7e51758ef63b9e6ee6697cf0733d3d34d08c509"

    def install
      bin.install "cedana-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the CedanaCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cedana/cedana-cli/releases/download/v0.2.6/cedana-cli_0.2.6_linux_amd64.tar.gz"
      sha256 "20ab1268768ab6495b70c4793c1dc0200b629da1d2ca3e5cc7c43a35cf6186f0"

      def install
        bin.install "cedana-cli"
      end
    end
  end
end
